CREATE TABLE IF NOT EXISTS posts (
    id INT(32) NOT NULL AUTO_INCREMENT,
    name VARCHAR(512) NOT NULL,
    content TEXT,
    author VARCHAR(512),
    category_id INT(32),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL ON UPDATE CASCADE
)