CREATE TABLE IF NOT EXISTS categories (
    id INT(32) NOT NULL AUTO_INCREMENT,
    name VARCHAR(512) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)